#!/usr/bin/env node
// Mint an authenticated Supabase session for a given user and print the
// @supabase/ssr auth cookies as JSON, so Playwright can inject them and browse
// the app AS that user — no password required.
//
// Usage:   node .claude/skills/impersonate-user/scripts/mint-session.mjs [email] [--out <file>]
// Default: ivo.pastin@gmail.com
//
// Reads from .env.local (must be run from / within the mytoys-crate project):
//   NEXT_PUBLIC_SUPABASE_URL
//   NEXT_PUBLIC_SUPABASE_ANON_KEY
//   SUPABASE_SERVICE_ROLE_KEY   (server-only secret, never NEXT_PUBLIC_)
//
// Output (stdout, single JSON line):
//   { "ok": true, "email": "...", "userId": "...", "cookies": [ { "name", "value" } ] }
//   { "ok": false, "error": "..." }   (and exit code 1)
//
// FAST PATH — `--out <file>`:
//   Also writes a ready-to-run Playwright function to <file>. Pass that path to
//   the browser_run_code_unsafe `filename` arg and it injects the cookies,
//   navigates to /app and returns the logged-in URL — one Playwright call, no
//   giant inline literal, no reading the cookies back into context.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";
import { createServerClient } from "@supabase/ssr";

const __dirname = dirname(fileURLToPath(import.meta.url));
// scripts -> impersonate-user -> skills -> .claude -> <project root>
const projectRoot = resolve(__dirname, "../../../..");

function loadEnv(path) {
  const env = {};
  let raw;
  try {
    raw = readFileSync(path, "utf8");
  } catch {
    return env;
  }
  for (const line of raw.split("\n")) {
    const m = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$/);
    if (!m) continue;
    let val = m[2];
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    env[m[1]] = val;
  }
  return env;
}

function fail(msg) {
  console.log(JSON.stringify({ ok: false, error: msg }));
  process.exit(1);
}

const env = { ...loadEnv(resolve(projectRoot, ".env.local")), ...process.env };

const SUPABASE_URL = env.NEXT_PUBLIC_SUPABASE_URL;
const ANON_KEY = env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
const SERVICE_ROLE_KEY = env.SUPABASE_SERVICE_ROLE_KEY;
const args = process.argv.slice(2);
const outIdx = args.indexOf("--out");
const outFile = outIdx !== -1 ? args[outIdx + 1] : null;
const email = args.find((a, i) => !a.startsWith("--") && i !== outIdx + 1) || "ivo.pastin@gmail.com";
const baseUrl = env.IMPERSONATE_BASE_URL || "http://localhost:3000";

if (!SUPABASE_URL || !ANON_KEY) {
  fail("Missing NEXT_PUBLIC_SUPABASE_URL or NEXT_PUBLIC_SUPABASE_ANON_KEY in .env.local");
}
if (!SERVICE_ROLE_KEY) {
  fail("Missing SUPABASE_SERVICE_ROLE_KEY in .env.local (add the service-role secret, no NEXT_PUBLIC_ prefix).");
}

// 1. Use the service-role key to generate a single-use magic-link token for the
//    target user. This proves identity without knowing their password.
const admin = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
  auth: { autoRefreshToken: false, persistSession: false },
});

const { data: linkData, error: linkErr } = await admin.auth.admin.generateLink({
  type: "magiclink",
  email,
});
if (linkErr) fail(`generateLink failed for ${email}: ${linkErr.message}`);

const tokenHash = linkData?.properties?.hashed_token;
const verifyType = linkData?.properties?.verification_type || "magiclink";
if (!tokenHash) fail(`No hashed_token returned for ${email} (does the user exist?)`);

// 2. Exchange the token on a @supabase/ssr server client. We hand it a cookie
//    adapter that simply captures whatever cookies the library decides to write
//    on sign-in — so we reproduce the EXACT cookie names, chunking and base64
//    encoding the running app expects, regardless of @supabase/ssr version.
const captured = [];
const ssr = createServerClient(SUPABASE_URL, ANON_KEY, {
  cookies: {
    getAll: () => [],
    setAll: (cookies) => {
      for (const { name, value } of cookies) captured.push({ name, value });
    },
  },
});

const { data: verifyData, error: verifyErr } = await ssr.auth.verifyOtp({
  token_hash: tokenHash,
  type: verifyType,
});
if (verifyErr) fail(`verifyOtp failed: ${verifyErr.message}`);
if (!captured.length) fail("Session established but no auth cookies were produced");

const playwrightCookies = captured.map((c) => ({
  name: c.name,
  value: c.value,
  domain: "localhost",
  path: "/",
  httpOnly: false,
  secure: false,
  sameSite: "Lax",
}));

// Fast path: emit a self-contained Playwright function. Feed its path to
// browser_run_code_unsafe `filename` — no require/import needed in the VM.
if (outFile) {
  const injector = `// auto-generated by mint-session.mjs — impersonates ${email}
async (page) => {
  const cookies = ${JSON.stringify(playwrightCookies)};
  await page.context().addCookies(cookies);
  await page.goto(${JSON.stringify(`${baseUrl}/app`)}, { waitUntil: "domcontentloaded" });
  return { url: page.url(), email: ${JSON.stringify(email)} };
}
`;
  writeFileSync(outFile, injector);
}

console.log(
  JSON.stringify({
    ok: true,
    email,
    userId: verifyData?.user?.id ?? null,
    injector: outFile || null,
    cookies: captured,
  })
);
