import type { Metadata } from "next";
import { Figtree, Geist } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body
        className={`${figtree.variable} ${figtree.className} antialiased bg-white px-[10px] py-[10px]`}
      >
        <div className="bg-background-primary text-font-primary px-[120px] py-[50px] rounded-[16px] h-[calc(100vh-20px)]">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
